### ISSUE TITLE
MiioTimeoutError: request timed out 

### ISSUE THREAD

**Issue by pcace** [Hypfer/valetudo-helper-miioota#13]
Hi there, 
is there a way to fix that problem? 
i am running a win11 and have a reseted Roborock S5 (no max) here wich i would love to flash.
there is no firewall / vpn running on the machine. the build is this: https://builder.dontvacuum.me/jobs/j63e29d3e07d76/569eabb972a01a851c5d74a51e291a34/v11_002034.pkg

```
Starting installer.
If you experience issues, make sure to disable your firewall and/or VPN.
Also, make sure that the robot is docked during the firmware update procedure.
If the install still fails, try turning the robot off and back on again and/or moving the laptop closer to it.

Robot discovery started...
Scan done.
Successfully discovered robot at 192.168.8.1
Reading firmware image..
Successfully read firmware image. Size: 75.65 MiB MD5Sum: 569eabb972a01a851c5d74a51e291a34

Listing for firmware download requests on http://192.168.8.82:51067/firmware
[2023-02-07T19:04:38.534Z] [ERROR] Error decrypting/parsing:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Codec.decodeIncomingMiioPacket (C:\snapshot\valetudo-helper-miioota\miio\Codec.js:76:32)
    at Socket.<anonymous> (C:\snapshot\valetudo-helper-miioota\miio\MiioSocket.js:53:54)
    at Socket.emit (node:events:526:28)
    at UDP.onMessage [as onmessage] (node:dgram:922:8) null <Buffer >
ERROR: Error while sending update command to robot
Error:
MiioTimeoutError: request timed out:{"method":"miIO.ota","params":{"mode":"normal","install":"1","app_url":"http://192.168.8.82:51067/firmware","file_md5":"569eabb972a01a851c5d74a51e291a34","proc":"dnld install"},"id":82768986}
    at Object.onTimeoutCallback (C:\snapshot\valetudo-helper-miioota\miio\MiioSocket.js:201:32)
    at Timeout._onTimeout (C:\snapshot\valetudo-helper-miioota\miio\MiioSocket.js:207:53)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)


Exiting..
```

if you have any idea what the problem could be, i am very happy to hear about it!
thanks a lot!

**Comment by Hypfer** [comment]
This message usually indicates that the firmware is too new to accept ota commands.

Did you make sure to do a full factory reset (not a wi-fi reset or a reboot)?
See https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Robots-Factory-Reset

**Comment by pcace** [comment]
embarassing... i did not read caruflly enough. I just did a wifi reset :/ 
Sorry for bothering.
