### ISSUE TITLE
[ERROR] Error decrypting/parsing:  SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by bentolor** [Hypfer/valetudo-helper-miioota#3]
Hi @Hypfer
Thanks for your great work & sorry I need to bother you: 
I have a 1st gen Robot which I used with FloleVac & on demand official Mi App. Later one I used to keep firmware up-to-date.

Unfortunately valetudo-helper-miioota doesn't seem to work for me and I'm unsure if this is due to an incompatbile firmware or sth. else. I'm on Arch linux & built and downloaded an `Build update package (for installation with python-miio/RRCC)` package.
 
I receive the following output w/o any delay immediately after emitting `Successfully read firmware image` (which I feel does not hit any typical real-life "timeout"). Robot has been reset/restarted.

Any hints?

```
 ! ~/Downloads >  ./valetudo-helper-miioota-amd64 install-firmware v11_004028.pkg
Starting installer.
If you experience issues, make sure to disable your firewall and/or VPN.
Also, make sure that the robot is docked during the firmware update procedure.
If the install still fails, try turning the robot off and back on again and/or moving the laptop closer to it.

Robot discovery started...
Scan done.
Successfully discovered robot at 192.168.8.1
Reading firmware image..
Successfully read firmware image. Size: 120.26 MiB MD5Sum: 50f9a169ad94e61b0f2501fd21423588

Listing for firmware download requests on http://192.168.8.244:36637/firmware
[2022-04-15T11:11:46.155Z] [ERROR] Error decrypting/parsing:  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Codec.decodeIncomingMiioPacket (/snapshot/valetudo-helper-miioota/miio/Codec.js:75:32)
    at Socket.<anonymous> (/snapshot/valetudo-helper-miioota/miio/MiioSocket.js:53:54)
    at Socket.emit (node:events:526:28)
    at UDP.onMessage [as onmessage] (node:dgram:922:8) null <Buffer >
ERROR: Error while sending update command to robot
Error:
MiioTimeoutError: request timed out:{"method":"miIO.ota","params":{"mode":"normal","install":"1","app_url":"http://192.168.8.244:36637/firmware","file_md5":"50f9a169ad94e61b0f2501fd21423588","proc":"dnld install"},"id":1800006243}
    at Object.onTimeoutCallback (/snapshot/valetudo-helper-miioota/miio/MiioSocket.js:193:32)
    at Timeout._onTimeout (/snapshot/valetudo-helper-miioota/miio/MiioSocket.js:199:53)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by Hypfer** [comment]
Are you sure that you've factory-reset the robot and not just the wifi configuration?

See: https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Robots-Factory-Reset

**Comment by bentolor** [comment]
My bad. Thanks, @Hypfer. Right on spot!
